import {flightSpeedStep,stoppingDistance,findLandingSite,createLandingPath,landingPathPoint} from './world/flight-handling.js';
import {renderRelative} from './world/large-world.js';
import {steerFighter,interceptPoint} from './world/dogfight.js';
import {createCombatEffects} from './world/combat-effects.js';
import {createRenderBudget} from './world/render-budget.js';
import {createGameAudio} from './audio/game-audio.js';
import {initLanguageSwitch,protectNames} from './i18n/index.js';
import {createWalkingMotion} from './world/walking-motion.js';
import {createWalkingCamera,keepCameraAboveGround} from './world/walking-camera.js';
import {solarRoute} from './world/solar.js';
import * as THREE from 'three';
import { createSystem, hashSeed, rng, STAR, solarExposure } from './world/procedural.js';
import { createUniverse } from './world/universe.js';
import { createSurface } from './world/surface.js';
import {loadAssetLibrary,createFighter,createExplorer} from './world/asset-library.js';
import { loadPlayerShip,updatePlayerShip } from './world/player-ship.js';
import { createPostProcessing } from './world/postprocessing.js';
import {easeFlight,flightQuaternion,departureFrame,rebaseFlightCamera} from './world/flight-transition.js';
import './style.css';
import { inject } from '@vercel/analytics';

const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp,vec=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
const canvas=$('space');
const siteNav=document.createElement('button');siteNav.className='surface-nav';siteNav.hidden=true;siteNav.onclick=()=>siteIndex++;$('hud').append(siteNav);
inject();
initLanguageSwitch();
let renderer;
try {renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch{$('loading').innerHTML='<p class="fatal">No se ha podido iniciar WebGL. Activa la aceleración gráfica del navegador y vuelve a cargar.</p>';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.15,70000),clock=new THREE.Clock();
const ambient=new THREE.HemisphereLight(0xc3e5ed,0x6d6355,2.1);scene.add(ambient);
const sun=new THREE.DirectionalLight(0xffe8c6,3.2);sun.position.set(-400,700,300);scene.add(sun);scene.add(sun.target);sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:1800});sun.shadow.bias=-.0005;sun.shadow.normalBias=.2;
const fill=new THREE.DirectionalLight(0x91c7e8,1.5);fill.position.set(90,-20,-90);scene.add(fill);
const player=new THREE.Group();scene.add(player);
const postprocessing=createPostProcessing(renderer,scene,camera);
const combatEffects=createCombatEffects(scene),renderBudget=createRenderBudget(renderer.getPixelRatio());
const forward=vec(0,0,-1),up=vec(0,1,0),right=vec(1,0,0),q=new THREE.Quaternion();
const scannedIds=new Set();
let seedText='NO-AI-2026',planets,universe,surface=null,selected=0,currentPlanet=null,mode='menu',previousMode='space';
let elapsed=0,gameTime=0,shield=100,boost=100,heat=0,speed=120,throttle=120,score=0,kills=0,lastDamage=-100,lastShot=-100,overheated=false,notifyTimer=0,discoveryTimer=0,scanTimer=0,scans=0,damageFlash=0;
let hullTemperature=20,solarWarning=0;
let firePointer=null,atmosphereCover=0,atmosphereRelease=0,atmosphereTint='#d7e2df';
const orbitNormal=vec(0,0,1);
let landingPreview=null,landingCheckTimer=0,turnYaw=0,turnPitch=0,siteIndex=0,siteSurface=null,hazardTimer=0;const siteMarkers=[];
let transition=null,queuedDestination=null,cinematic=false,firstPerson=false,firing=false,touchBoost=false,walkingYaw=0,walkingPitch=0,joystickId=null;
let avatar=null,orbitPointer=null;const walkingCamera=createWalkingCamera(),walkingMotion=createWalkingMotion();
const walker=vec(),pointer={x:0,y:0},keys=new Set(),enemies=[],bullets=[],particles=[],planetMarkers=[],scanMarkers=[];
let battleWave=0,battleDelay=0;const gameAudio=createGameAudio();
const laserGeometry=new THREE.CylinderGeometry(.075,.075,4,5);laserGeometry.rotateX(Math.PI/2);
const blueLaser=new THREE.MeshBasicMaterial({color:0xb5f9ed}),redLaser=new THREE.MeshBasicMaterial({color:0xff7752}),particleGeometry=new THREE.IcosahedronGeometry(.3,0),particleMaterial=new THREE.MeshBasicMaterial({color:0xffd49c});
// A contact shadow anchors a landed ship even outside the directional shadow map.
const contactShadow=new THREE.Mesh(new THREE.CircleGeometry(6.5,48),new THREE.MeshBasicMaterial({color:0x1e342c,transparent:true,opacity:.16,depthWrite:false}));contactShadow.rotation.x=-Math.PI/2;contactShadow.visible=false;scene.add(contactShadow);
const dustRandom=rng(7281),dustPositions=new Float32Array(600*3);for(let i=0;i<dustPositions.length;i++)dustPositions[i]=(dustRandom()-.5)*260;
const dustGeometry=new THREE.BufferGeometry();dustGeometry.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({size:.1,color:0xd7f0df,transparent:true,opacity:.6}));scene.add(dust);

function playSound(type){gameAudio.play(type);}
function notify(text,duration=3){$('notification').textContent=text;$('notification').classList.add('show');notifyTimer=duration;}
function saveProgress(){try{localStorage.setItem(`no-ai-sky:${seedText}`,JSON.stringify({discovered:planets.map(p=>p.discovered),scans,scannedIds:[...scannedIds]}));}catch{/* Storage can be unavailable in private embedded browsers. */}}
function clearCombat(){combatEffects.clear();for(const e of enemies){scene.remove(e.mesh);e.marker.remove();}enemies.length=0;for(const b of bullets)scene.remove(b.mesh);bullets.length=0;for(const p of particles)scene.remove(p.mesh);particles.length=0;battleWave=0;battleDelay=0;$('mission-hud').hidden=true;}
function rebuildUniverse(seed){clearCombat();universe?.dispose();surface?.dispose();surface=null;seedText=seed.trim()||'NO-AI-2026';$('seed').value=seedText;planets=createSystem(seedText);protectNames([seedText,...planets.map(p=>p.name)]);selected=0;scans=0;scannedIds.clear();try{const saved=JSON.parse(localStorage.getItem(`no-ai-sky:${seedText}`)||'null');if(saved){planets.forEach((p,i)=>p.discovered=!!saved.discovered?.[i]);scans=Number.isFinite(saved.scans)?saved.scans:0;for(const id of saved.scannedIds||[])scannedIds.add(id);}}catch{}
  universe=createUniverse(planets,seedText);scene.add(universe.group);currentPlanet=null;for(const m of planetMarkers)m.remove();planetMarkers.length=0;for(const p of planets){const marker=document.createElement('div');marker.className='planet-marker';marker.innerHTML='<div class="diamond"></div><strong></strong><small></small>';$('markers').append(marker);planetMarkers.push(marker);}renderCards();selectPlanet(0);$('system-name').textContent=`SISTEMA ${hashSeed(seedText).toString(16).slice(0,5).toUpperCase()}`;
}
function orbStyle(p){return `--planet-land:${p.land};--planet-sea:${p.ocean}`;}
function renderCards(){$('world-cards').innerHTML='';planets.forEach((p,i)=>{const b=document.createElement('button');b.className=`world-card${i===selected?' active':''}`;b.setAttribute('aria-label',`Seleccionar ${p.name}, ${p.type.toLowerCase()}`);b.innerHTML=`<span class="world-orb" style="${orbStyle(p)}"></span><span><strong>${p.name}</strong><small>${p.type}</small></span><em>0${i+1}</em>`;b.onclick=()=>selectPlanet(i);$('world-cards').append(b);});}
function selectPlanet(index){selected=index;$('hero-planet-name').textContent=planets[index].name;$('hero-planet-type').textContent=planets[index].type;[...$('world-cards').children].forEach((b,i)=>b.classList.toggle('active',i===index));planetMarkers.forEach((m,i)=>m.classList.toggle('selected',i===index));}
function setMode(next){mode=next;document.body.classList.toggle('playing',next!=='menu');document.body.classList.toggle('surface',!!surface&&universe.group.visible===false);document.body.classList.toggle('walking',next==='walking');$('hangar').hidden=next!=='menu';$('hud').hidden=next==='menu'||cinematic;player.visible=true;updateUI();}
function resetInput(){walkingMotion.clearInput();turnYaw=turnPitch=0;orbitPointer=null;keys.clear();pointer.x=pointer.y=0;firing=false;touchBoost=false;}
function startGame(){gameAudio.unlock();hullTemperature=20;solarWarning=0;atmosphereCover=atmosphereRelease=0;clearCombat();surface?.dispose();surface=null;currentPlanet=null;universe.group.visible=true;renderer.toneMappingExposure=1.12;scene.fog=null;contactShadow.visible=false;sun.castShadow=false;ambient.color.set(0xc3e5ed);ambient.groundColor.set(0x6d6355);ambient.intensity=2.1;sun.color.set(0xffe8c6);sun.intensity=3.2;fill.intensity=1.5;shield=boost=100;heat=0;overheated=false;speed=throttle=120;score=kills=0;gameTime=0;lastDamage=-100;lastShot=-100;firstPerson=false;resetInput();$('modal').hidden=true;const p=planets[selected],pos=vec(...p.position);player.position.copy(pos).add(vec(-230,20,p.radius+710));player.lookAt(pos);player.rotateY(Math.PI);camera.position.copy(player.position).add(vec(0,4.2,18).applyQuaternion(player.quaternion));camera.up.copy(up);camera.lookAt(pos);setMode('space');notify('EL UNIVERSO TE ESPERA · E PARA VISITAR UN PLANETA',5);}

function modal(kicker,title,body,action,handler,showReturn=false){$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-action').innerHTML=`${action}<span>↗</span>`;$('modal-action').onclick=handler;$('return-hangar').hidden=!showReturn;$('modal').hidden=false;$('modal-action').focus();}
const controlsHTML='<div class="control-row"><span>Orientar nave / mirar</span><kbd>RATÓN / FLECHAS</kbd></div><div class="control-row"><span>Velocidad / caminar</span><kbd>W A S D</kbd></div><div class="control-row"><span>Propulsión / correr</span><kbd>SHIFT</kbd></div><div class="control-row"><span>Saltar a pie</span><kbd>ESPACIO</kbd></div><div class="control-row"><span>Freno de la nave</span><kbd>X</kbd></div><div class="control-row"><span>Cambiar lugar de interés</span><kbd>L</kbd></div><div class="control-row"><span>Visitar / aterrizar / salir / subir</span><kbd>E</kbd></div><div class="control-row"><span>Despegar / volver al espacio</span><kbd>R</kbd></div><div class="control-row"><span>Escanear flora, fauna y minerales</span><kbd>F</kbd></div><div class="control-row"><span>Seleccionar planeta / Atlas</span><kbd>1–9 / TAB</kbd></div><div class="control-row"><span>Disparar / activar combate orbital</span><kbd>CLIC, ESPACIO / B</kbd></div><div class="control-row"><span>Cámara / modo fotografía / pausa</span><kbd>V / C / ESC</kbd></div><p>Centra el cursor para dejar de girar. E activa una aproximación automática desde el espacio; en la superficie busca una zona seca y aterriza. Pulsa E otra vez para salir de la nave. Acércate a ella para volver a subir. En móvil, usa el joystick y los botones E, R, SCAN y BOOST.</p><p class="model-credit">Nave: <a href="https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5" target="_blank" rel="noopener noreferrer">Rusty Spaceship – Orange</a>, <a href="https://sketchfab.com/sousinho" target="_blank" rel="noopener noreferrer">Sousinho</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a>. Texturas optimizadas y adaptación al vuelo. <a href="/licenses/rusty-spaceship.txt" target="_blank" rel="noopener noreferrer">Créditos</a>. Personajes, enemigos y rocas: <a href="https://quaternius.com/packs/ultimatespacekit.html" target="_blank" rel="noopener noreferrer">Quaternius · CC0</a>.</p>';
function pause(){if(['menu','paused','generating','transit','descent','ascent','landing','takeoff'].includes(mode))return;previousMode=mode;mode='paused';resetInput();modal('UN MOMENTO ENTRE ESTRELLAS','Tu viaje continúa aquí.',controlsHTML,'CONTINUAR',resume,true);}
function resume(){if(mode==='paused')setMode(previousMode);$('modal').hidden=true;resetInput();}
function showHelp(){if(['generating','transit','descent','ascent','landing','takeoff'].includes(mode))return;const wasMenu=mode==='menu';if(!wasMenu){previousMode=mode;mode='paused';resetInput();}modal('MANUAL DEL VIAJERO','No hay un único camino.',controlsHTML,wasMenu?'ENTENDIDO':'CONTINUAR',()=>wasMenu?$('modal').hidden=true:resume());}
function showAtlas(){if(['generating','transit','descent','ascent','landing','takeoff'].includes(mode))return;const wasMenu=mode==='menu';if(!wasMenu){previousMode=mode;mode='paused';resetInput();}const rows=planets.map((p,i)=>`<button class="atlas-row${selected===i?' selected':''}" data-planet="${i}" aria-label="Destino ${p.name}"><span class="world-orb" style="${orbStyle(p)}"></span><span><strong>${p.name}</strong><small>${p.type} · ${p.temperature} · ${p.moons} LUNAS</small><small>${p.discovered?'DESCUBIERTO':'SIN EXPLORAR'} / VIDA ${p.life.toUpperCase()}</small></span><span>0${i+1} ↗</span></button>`).join('');modal(`ATLAS / SEMILLA ${seedText}`,'Elige tu próximo horizonte.',rows,`VIAJAR A ${planets[selected].name.toUpperCase()}`,()=>{if(wasMenu)startGame();else resume();if(surface){queuedDestination=selected;beginAscent();}else beginTravel();});for(const b of $('modal-body').querySelectorAll('[data-planet]'))b.onclick=()=>{selectPlanet(Number(b.dataset.planet));$('modal-body').querySelectorAll('[data-planet]').forEach(el=>el.classList.toggle('selected',Number(el.dataset.planet)===selected));$('modal-action').innerHTML=`VIAJAR A ${planets[selected].name.toUpperCase()}<span>↗</span>`;};}
function returnMenu(){atmosphereCover=atmosphereRelease=0;clearCombat();surface?.dispose();surface=null;universe.group.visible=true;renderer.toneMappingExposure=1.12;scene.fog=null;sun.castShadow=false;sun.position.set(-400,700,300);sun.target.position.set(0,0,0);sun.color.set(0xffe8c6);ambient.color.set(0xc3e5ed);ambient.intensity=2.1;fill.intensity=1.5;contactShadow.visible=false;$('modal').hidden=true;$('transition').hidden=true;$('discovery').hidden=true;cinematic=false;document.querySelector('.topbar').hidden=false;resetInput();setMode('menu');}
function showTransition(kicker,title,detail){$('transition').hidden=false;$('transition-kicker').textContent=kicker;$('transition-title').textContent=title;$('transition-detail').textContent=detail;$('transition-progress').style.width='0%';if(mode==='transit')playSound('warp');}
function beginTravel(){
  if(mode!=='space')return;clearCombat();resetInput();atmosphereRelease=0;
  const p=planets[selected],center=vec(...p.position),normal=player.position.clone().sub(center).normalize();if(normal.lengthSq()<.1)normal.set(0,0,1);orbitNormal.copy(normal);atmosphereTint=p.horizon;
  transition={time:0,duration:1.6,startCover:atmosphereCover,start:player.position.clone(),end:center.clone().addScaledVector(normal,p.radius+90),look:center,startQ:player.quaternion.clone(),endQ:flightQuaternion(normal.clone().negate()),startFov:camera.fov};
  transition.end.copy(center).addScaledVector(normal,p.landable===false?p.radius+420:p.radius+90);transition.route=solarRoute(transition.start,transition.end);
  setMode('transit');showTransition('PULSO INTERPLANETARIO',p.name,p.landable===false?'APROXIMACIÓN ORBITAL · SIN SUPERFICIE SÓLIDA':'ATRAVESANDO LA CAPA ATMOSFÉRICA');
}
async function enterAtmosphere(){if(planets[selected].landable===false){atmosphereCover=0;atmosphereRelease=0;speed=throttle=0;setMode('space');$('transition').hidden=true;discoverOrbital();return;}atmosphereCover=1;setMode('generating');$('transition-detail').textContent='CRUZANDO EL MANTO DE NUBES';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
  try{surface?.dispose();surface=createSurface(planets[selected],orbitNormal);scene.add(surface.group);currentPlanet=planets[selected];for(const resource of surface.resources)resource.scanned=scannedIds.has(`${currentPlanet.id}:${resource.id}`);universe.group.visible=false;scene.fog=new THREE.FogExp2(currentPlanet.horizon,.00028);ambient.color.set(currentPlanet.sky);ambient.groundColor.set(currentPlanet.ink);ambient.intensity=1.2;sun.color.set(currentPlanet.sun);sun.intensity=2.5;renderer.toneMappingExposure=1.02;sun.castShadow=true;fill.intensity=.4;rebaseFlightCamera(camera,player,vec(0,590,1050),new THREE.Quaternion().setFromEuler(new THREE.Euler(-.45,0,0)));transition={time:0,duration:2.2,start:player.position.clone(),end:vec(0,82,130),startQ:player.quaternion.clone(),endQ:new THREE.Quaternion()};setMode('descent');showTransition('ENTRADA ATMOSFÉRICA',currentPlanet.name,`${currentPlanet.type} · ${currentPlanet.temperature} · VIDA ${currentPlanet.life.toUpperCase()}`);}catch(error){console.error(error);notify('NO SE PUDO GENERAR LA SUPERFICIE · REINTENTA DESDE EL ATLAS',6);surface?.dispose();surface=null;universe.group.visible=true;renderer.toneMappingExposure=1.12;scene.fog=null;sun.castShadow=false;atmosphereRelease=.55;$('transition').hidden=true;setMode('space');}
}
function refreshLandingPreview(){
  const origin=player.position.clone().addScaledVector(forward.clone().applyQuaternion(player.quaternion),Math.min(75,speed*.12));
  landingPreview=findLandingSite(origin,surface.height,{obstacles:surface.obstacles,hazardAt:surface.hazardAt});landingCheckTimer=.35;
  surface.landingEffects.setGuide(landingPreview,!cinematic);
}
function beginLanding(){
  if(mode!=='surface')return;refreshLandingPreview();
  if(!landingPreview){notify('SIN ZONA SEGURA · BUSCA TERRENO LLANO Y DESPEJADO',4);return;}
  const target=vec(landingPreview.x,landingPreview.y,landingPreview.z),path=createLandingPath(player.position,target,surface.height,surface.obstacles);
  const yaw=new THREE.Euler().setFromQuaternion(player.quaternion,'YXZ').y;
  transition={time:0,duration:path.duration,start:player.position.clone(),end:target,path,startQ:player.quaternion.clone(),endQ:new THREE.Quaternion().setFromEuler(new THREE.Euler(0,yaw,0))};
  setMode('landing');resetInput();notify('APROXIMACIÓN A LA ZONA MARCADA · TREN DESPLEGADO',3);
}

function disembark(){walker.copy(player.position).add(vec(8,0,3).applyQuaternion(player.quaternion));walkingMotion.reset(walker,surface.height);walkingYaw=new THREE.Euler().setFromQuaternion(player.quaternion,'YXZ').y;walkingPitch=-.15;walkingCamera.reset();avatar.mesh.position.copy(walker).add(vec(0,-1.8,0));avatar.mesh.rotation.y=walkingYaw+Math.PI;avatar.play('Idle');resetInput();setMode('walking');notify('PRIMEROS PASOS · F PARA ESCANEAR TU ENTORNO',4);}
function boardShip(){if(walker.distanceTo(player.position)>20){notify('ACÉRCATE A TU NAVE PARA SUBIR A BORDO',3);return;}resetInput();setMode('landed');notify('A BORDO · R PARA DESPEGAR',3);}
function takeoff(){if(mode==='walking'){if(walker.distanceTo(player.position)>20){notify('VUELVE A TU NAVE PARA DESPEGAR',3);return;}boardShip();}if(mode!=='landed')return;const end=player.position.clone().add(vec(0,38,-35).applyQuaternion(player.quaternion));transition={time:0,duration:1.1,start:player.position.clone(),end};contactShadow.visible=false;setMode('takeoff');resetInput();playSound('takeoff');notify('PROPULSORES ACTIVOS · DESPEGANDO',3);}
function beginAscent(){
  if(!surface||!['surface','landed','walking'].includes(mode))return;
  if(mode==='walking'&&walker.distanceTo(player.position)>20){notify('VUELVE A TU NAVE PARA ABANDONAR EL PLANETA',4);queuedDestination=null;return;}
  clearCombat();resetInput();contactShadow.visible=false;atmosphereTint=currentPlanet.horizon;
  const heading=forward.clone().applyQuaternion(player.quaternion);heading.y=0;if(heading.lengthSq()<.01)heading.set(0,0,-1);heading.normalize();
  const climb=heading.clone().multiplyScalar(.42).add(vec(0,.91,0)).normalize();
  transition={time:0,duration:1.8,start:player.position.clone(),end:player.position.clone().addScaledVector(climb,1900),startQ:player.quaternion.clone(),endQ:flightQuaternion(climb),startFov:camera.fov};
  setMode('ascent');showTransition('ASCENSO ORBITAL',currentPlanet.name,'ATRAVESANDO LAS NUBES · RUMBO AL ESPACIO');
}
function returnToSpace(){const p=currentPlanet;orbitNormal.copy(surface.frame.toPlanet(player.position).normalize());surface.dispose();surface=null;currentPlanet=null;universe.group.visible=true;renderer.toneMappingExposure=1.12;scene.fog=null;ambient.color.set(0xc3e5ed);ambient.groundColor.set(0x6d6355);ambient.intensity=2.1;sun.color.set(0xffe8c6);sun.castShadow=false;sun.position.set(-400,700,300);sun.target.position.set(0,0,0);fill.intensity=1.5;contactShadow.visible=false;const exit=departureFrame(p,orbitNormal);rebaseFlightCamera(camera,player,exit.position,exit.quaternion);speed=throttle=360;atmosphereCover=1;atmosphereRelease=.65;resetInput();$('transition').hidden=true;for(const m of scanMarkers)m.element.remove();scanMarkers.length=0;setMode('space');notify('ÓRBITA ALCANZADA · ELIGE TU PRÓXIMO MUNDO',4);if(queuedDestination!==null){selectPlanet(queuedDestination);queuedDestination=null;beginTravel();}}
function discoverOrbital(){const p=planets[selected];p.discovered=true;saveProgress();renderCards();notify(`${p.name.toUpperCase()} · GIGANTE SIN SUPERFICIE SÓLIDA · EXPLORACIÓN ORBITAL`,5);}
function action(){if(mode==='space')beginTravel();else if(mode==='surface')beginLanding();else if(mode==='landed')disembark();else if(mode==='walking')boardShip();}
function discover(){const first=!currentPlanet.discovered;currentPlanet.discovered=true;saveProgress();$('discovery-name').textContent=currentPlanet.name;$('discovery-detail').textContent=`${currentPlanet.type} / ${currentPlanet.temperature} / ATMÓSFERA ${currentPlanet.atmosphere.toUpperCase()}`;$('discovery').firstElementChild.textContent=first?'DESCUBIERTO POR TI':'BIENVENIDO DE NUEVO';$('discovery').hidden=false;discoveryTimer=5;renderCards();}
function scan(){if(!surface||!['walking','landed','surface'].includes(mode)){notify('ESCÁNER DISPONIBLE EN LA SUPERFICIE DE UN PLANETA',3);return;}const origin=mode==='walking'?walker:player.position;const nearby=surface.resources.filter(r=>r.position.distanceTo(origin)<180).sort((a,b)=>a.position.distanceToSquared(origin)-b.position.distanceToSquared(origin)).slice(0,10);let fresh=0;for(const r of nearby)if(!r.scanned){r.scanned=true;scannedIds.add(`${currentPlanet.id}:${r.id}`);fresh++;}scans+=fresh;saveProgress();for(const m of scanMarkers)m.element.remove();scanMarkers.length=0;for(const r of nearby){const element=document.createElement('div');element.className='scan-marker';element.innerHTML=`${r.name}<small>${r.type}</small>`;$('markers').append(element);scanMarkers.push({element,resource:r});}scanTimer=9;$('scan-wave').classList.remove('active');void $('scan-wave').offsetWidth;$('scan-wave').classList.add('active');playSound('scan');notify(fresh?`${fresh} HALLAZGOS AÑADIDOS AL ATLAS`:'ESCANEO COMPLETADO · EXPLORA MÁS LEJOS PARA NUEVOS HALLAZGOS',3);}

function emitLaser(position,direction,enemy=false){const mesh=new THREE.Mesh(laserGeometry,enemy?redLaser:blueLaser);mesh.position.copy(position);mesh.quaternion.setFromUnitVectors(forward,direction);scene.add(mesh);bullets.push({mesh,previous:position.clone(),velocity:direction.clone().multiplyScalar(enemy?650:500+speed*.36),enemy,life:enemy?2.5:2.1});}
function fire(){if(gameTime-lastShot<.15||overheated)return;lastShot=gameTime;heat=Math.min(100,heat+8);if(heat>=100){overheated=true;notify('LÁSER SOBRECALENTADO · ENFRIANDO',2);}const direction=forward.clone().applyQuaternion(player.quaternion);let target=null,best=.98;for(const e of enemies){const dot=e.mesh.position.clone().sub(player.position).normalize().dot(direction);if(dot>best){best=dot;target=e;}}for(const side of [-1,1]){const pos=vec(side*1.25,.15,-5.8).applyQuaternion(player.quaternion).add(player.position);emitLaser(pos,target?target.mesh.position.clone().sub(pos).normalize():direction);}playSound('laser');}
function explode(position){playSound('explosion');combatEffects.burst(position,true);}
function damage(amount){if(mode!=='space'&&mode!=='surface')return;combatEffects.burst(player.position);shield=Math.max(0,shield-amount);lastDamage=gameTime;damageFlash=.4;playSound('hit');if(shield<=0){previousMode=mode;mode='paused';resetInput();modal('BALIZA DE EMERGENCIA ACTIVADA','Todo viaje tiene otra oportunidad.',`<p>La nave ha perdido sus escudos. Tu registro de descubrimientos está guardado. Puedes volver al espacio y continuar la exploración.</p><p>${kills} interceptores derribados · ${score} unidades</p>`,'RECUPERAR LA NAVE',startGame,true);}}
function spawnWave(){if(mode!=='space')return;battleWave++;const random=rng(hashSeed(seedText)+battleWave*3451);for(let i=0;i<battleWave+3;i++){const mesh=createFighter(i),offset=vec((i-(battleWave+2)/2)*45,(random()-.5)*50,-180-random()*90).applyQuaternion(player.quaternion);mesh.position.copy(player.position).add(offset);scene.add(mesh);const marker=document.createElement('div');marker.className='enemy-marker';marker.innerHTML='<small></small>';$('markers').append(marker);enemies.push({mesh,marker,hp:3,cooldown:3+random()*4,phase:random()*6.28,dead:false});}$('mission-hud').hidden=false;notify(`PATRULLA HOSTIL · OLEADA ${battleWave} / 3`,4);}
function segmentHit(a,b,p,r){const ab=b.clone().sub(a),len=ab.lengthSq(),t=len?clamp(p.clone().sub(a).dot(ab)/len,0,1):0;return ab.multiplyScalar(t).add(a).distanceToSquared(p)<r*r;}
function updateCombat(dt){
  const playerVelocity=forward.clone().applyQuaternion(player.quaternion).multiplyScalar(speed*.36),bodies=[{position:[0,0,0],radius:STAR.exclusionRadius},...planets];
  for(const e of enemies){const approach=steerFighter(e,player.position,playerVelocity,elapsed,dt,bodies);e.cooldown-=dt;if(e.cooldown<=0&&approach.distance<650&&approach.aligned&&!approach.retreat){const aim=interceptPoint(e.mesh.position,player.position,playerVelocity,650);emitLaser(e.mesh.position,aim.sub(e.mesh.position).normalize(),true);e.burst=(e.burst||0)+1;e.cooldown=e.burst%3===0?2.5:.25;}}

  for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.previous.copy(b.mesh.position);b.mesh.position.addScaledVector(b.velocity,dt);b.life-=dt;if(b.enemy){if(segmentHit(b.previous,b.mesh.position,player.position,2)){b.life=0;damage(12);}}else{for(const e of enemies)if(!e.dead&&segmentHit(b.previous,b.mesh.position,e.mesh.position,3.5)){e.hp--;b.life=0;combatEffects.burst(e.mesh.position);if(e.hp<=0){e.dead=true;explode(e.mesh.position);kills++;score+=300;}else playSound('hit');break;}}if(b.life<=0){scene.remove(b.mesh);bullets.splice(i,1);}}
  for(let i=enemies.length-1;i>=0;i--)if(enemies[i].dead){scene.remove(enemies[i].mesh);enemies[i].marker.remove();enemies.splice(i,1);}
  if(battleWave&&!enemies.length&&mode==='space'){battleDelay+=dt;if(battleDelay>3){battleDelay=0;if(battleWave<3)spawnWave();else{battleWave=0;$('mission-hud').hidden=true;score+=1000;shield=100;notify('SECTOR DESPEJADO · +1000 UNIDADES',4);}}}
  for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.scale.multiplyScalar(1-dt);if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);}}
}

function followCamera(dt,immediate=false){const direction=forward.clone().applyQuaternion(player.quaternion);let target;if(firstPerson&&['space','surface'].includes(mode)){target=player.position.clone().add(vec(0,1.6,-4).applyQuaternion(player.quaternion));}else target=player.position.clone().add(vec(0,innerWidth<700?5.7:4.5,innerWidth<700?27:20).applyQuaternion(player.quaternion));if(surface)target=keepCameraAboveGround(player.position,target,surface.height,1);camera.position.lerp(target,immediate?1:1-Math.exp(-7*dt));if(surface)camera.position.copy(keepCameraAboveGround(player.position,camera.position,surface.height,1));camera.up.copy(up).applyQuaternion(player.quaternion);camera.lookAt(player.position.clone().addScaledVector(direction,110));}
function updateSolarHeat(dt){
 const distance=player.position.length(),exposure=solarExposure(distance);solarWarning=Math.max(0,solarWarning-dt);
 hullTemperature=clamp(hullTemperature+((exposure>0?12+exposure*100:0)-18)*dt,20,200);
 if(exposure>0&&solarWarning===0){notify('PELIGRO SOLAR · CALOR EXTREMO · ALÉJATE DEL SOL',3);solarWarning=4;}
 if(hullTemperature>110&&gameTime-lastDamage>.5)damage((hullTemperature-100)*.08);
 if(distance<STAR.exclusionRadius){const outward=player.position.clone().normalize();if(outward.lengthSq()<.1)outward.set(0,0,1);player.position.copy(outward).multiplyScalar(STAR.exclusionRadius+10);player.quaternion.copy(flightQuaternion(outward));speed=throttle=560;resetInput();notify('PROTECCIÓN TÉRMICA · EVASIÓN SOLAR AUTOMÁTICA',4);}
}
function updateFlight(dt){const onSurface=mode==='surface',braking=keys.has('KeyX'),boostOn=!braking&&(keys.has('ShiftLeft')||keys.has('ShiftRight')||touchBoost)&&boost>1;const max=onSurface?540:560;if(keys.has('KeyW'))throttle=clamp(throttle+260*dt,onSurface?0:25,max);if(keys.has('KeyS'))throttle=clamp(throttle-420*dt,onSurface?0:25,max);if(braking)throttle=0;speed=flightSpeedStep(speed,throttle,{boost:boostOn,brake:braking,surface:onSurface,dt});boost=clamp(boost+(boostOn?-14:22)*dt,0,100);
  const yaw=-pointer.x*.73+(keys.has('KeyA')||keys.has('ArrowLeft')?.85:0)-(keys.has('KeyD')||keys.has('ArrowRight')?.85:0),pitch=-pointer.y*.57+(keys.has('ArrowUp')?.65:0)-(keys.has('ArrowDown')?.65:0),roll=(keys.has('KeyQ')?.8:0)-(keys.has('KeyE')?.8:0);
  turnYaw=THREE.MathUtils.damp(turnYaw,yaw,7,dt);turnPitch=THREE.MathUtils.damp(turnPitch,pitch,7,dt);player.quaternion.multiply(q.setFromAxisAngle(up,turnYaw*dt));player.quaternion.multiply(q.setFromAxisAngle(right,turnPitch*dt));if(!onSurface)player.quaternion.multiply(q.setFromAxisAngle(forward,roll*dt));
  if(onSurface){const euler=new THREE.Euler().setFromQuaternion(player.quaternion,'YXZ');euler.x=clamp(euler.x,-.7,.9);euler.z=THREE.MathUtils.damp(euler.z,clamp(-turnYaw*.22,-.2,.2),4,dt);player.quaternion.setFromEuler(euler);}
  const direction=forward.clone().applyQuaternion(player.quaternion);player.position.addScaledVector(direction,speed*(onSurface?.3:.36)*dt);
  if(onSurface){const floor=Math.max(surface.height(player.position.x,player.position.z),1)+5;if(player.position.y<floor){player.position.y=floor;const e=new THREE.Euler().setFromQuaternion(player.quaternion,'YXZ');e.x=Math.max(.05,e.x);player.quaternion.setFromEuler(e);}if(player.position.y>1100||Math.hypot(player.position.x,player.position.z)>surface.terrain.size*.45){beginAscent();return;}}
  else{updateSolarHeat(dt);if(mode!=='space')return;for(let i=0;i<planets.length;i++){const p=planets[i];if(player.position.distanceTo(vec(...p.position))<p.radius+65){if(p.landable===false){const normal=player.position.clone().sub(vec(...p.position)).normalize();player.position.copy(vec(...p.position)).addScaledVector(normal,p.radius+110);player.quaternion.copy(flightQuaternion(normal));notify('PRESIÓN EXTREMA · ASCENSO DE SEGURIDAD',3);return;}selectPlanet(i);beginTravel();return;}}if(gameTime-lastDamage>1){for(const rock of universe.asteroids)if(player.position.distanceToSquared(rock.position)<(rock.radius+2)**2){damage(15);player.position.addScaledVector(player.position.clone().sub(rock.position).normalize(),rock.radius+5);notify('IMPACTO DE ASTEROIDE',2);break;}}}
  if((firing||keys.has('Space'))&&mode==='space')fire();
  for(const child of player.children)if(child.userData.engine)child.scale.setScalar((boostOn?3.4:1.7)+Math.sin(elapsed*38)*.12);
  for(let i=0;i<dustPositions.length;i+=3){dustPositions[i]-=direction.x*speed*.36*dt;dustPositions[i+1]-=direction.y*speed*.36*dt;dustPositions[i+2]-=direction.z*speed*.36*dt;for(let j=0;j<3;j++){if(dustPositions[i+j]>130)dustPositions[i+j]-=260;if(dustPositions[i+j]<-130)dustPositions[i+j]+=260;}}dustGeometry.attributes.position.needsUpdate=true;
  camera.fov=THREE.MathUtils.damp(camera.fov,boostOn?78:60,3,dt);camera.updateProjectionMatrix();followCamera(dt);
}
function updateWalking(dt){
 walkingYaw+=((joystickId!==null?-pointer.x*.95:0)+(keys.has('ArrowLeft')?.9:0)-(keys.has('ArrowRight')?.9:0))*dt;
 walkingPitch=clamp(walkingPitch+((keys.has('ArrowUp')?.65:0)-(keys.has('ArrowDown')?.65:0))*dt,-.75,.55);
 const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight')||touchBoost;
 const move=vec((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));if(joystickId!==null)move.z=pointer.y;
 if(move.lengthSq()>1)move.normalize();move.applyAxisAngle(up,walkingYaw);
 walkingMotion.update(walker,move,sprint?30:10,dt,surface.height,surface.terrain.size*.44);
 avatar.mesh.position.copy(walker).add(vec(0,-1.8,0));if(move.lengthSq()>.001){const facing=new THREE.Quaternion().setFromAxisAngle(up,Math.atan2(move.x,move.z));avatar.mesh.quaternion.slerp(facing,1-Math.exp(-12*dt));}
 avatar.play(walkingMotion.grounded&&walkingMotion.speed>.2?(sprint?'Run':'Walk'):'Idle');avatar.mixer.update(dt);
 walkingCamera.update(camera,walker,walkingYaw,walkingPitch,sprint&&move.lengthSq()>.001,dt,surface.height);speed=walkingMotion.speed;
}
function updateTransition(dt){
  if(!transition)return;transition.time+=dt;
  const t=clamp(transition.time/transition.duration,0,1),smooth=easeFlight(t);
  $('transition-progress').style.width=`${Math.round(t*100)}%`;if(mode==='transit'&&transition.route)transition.route.getPoint(smooth,player.position);else if(mode==='landing'&&transition.path)landingPathPoint(transition.path,t,player.position);else player.position.lerpVectors(transition.start,transition.end,smooth);
  if(mode==='transit'){
    player.quaternion.slerpQuaternions(transition.startQ,transition.endQ,easeFlight(clamp(t*1.6,0,1)));
    camera.fov=THREE.MathUtils.lerp(transition.startFov,66,smooth)+Math.sin(t*Math.PI)*14;
    atmosphereCover=planets[selected].landable===false?0:Math.max(transition.startCover*(1-easeFlight(clamp(t/.4,0,1))),easeFlight(clamp((t-.55)/.45,0,1)));
  }else if(mode==='descent'){
    player.quaternion.slerpQuaternions(transition.startQ,transition.endQ,smooth);camera.fov=66-6*smooth;
    atmosphereCover=1-easeFlight(clamp((t-.08)/.72,0,1));
  }else if(mode==='landing'){
    player.position.y=Math.max(player.position.y,surface.height(player.position.x,player.position.z)+1.48);player.quaternion.slerpQuaternions(transition.startQ,transition.endQ,smooth);camera.fov=THREE.MathUtils.damp(camera.fov,60,5,dt);
  }else if(mode==='ascent'){
    player.quaternion.slerpQuaternions(transition.startQ,transition.endQ,easeFlight(clamp(t*1.5,0,1)));
    camera.fov=THREE.MathUtils.lerp(transition.startFov,66,smooth)+Math.sin(t*Math.PI)*6;
    atmosphereCover=easeFlight(clamp((t-.32)/.68,0,1));
  }
  followCamera(dt);camera.updateProjectionMatrix();speed=mode==='landing'?Math.round((1-t)*30):mode==='takeoff'?30:Math.round(360+Math.sin(t*Math.PI)*790);
  if(t>=1){const finished=mode;transition=null;if(finished==='transit')enterAtmosphere();else if(finished==='descent'){$('transition').hidden=true;player.rotation.set(0,0,0);speed=throttle=0;setMode('surface');discover();notify('E PARA ATERRIZAR · R PARA VOLVER AL ESPACIO',4);}else if(finished==='landing'){speed=0;contactShadow.position.copy(player.position);contactShadow.position.y=surface.height(player.position.x,player.position.z)+.06;contactShadow.visible=true;setMode('landed');notify('ATERRIZAJE COMPLETADO · E PARA SALIR DE LA NAVE',4);playSound('landing');}else if(finished==='takeoff'){speed=throttle=45;setMode('surface');}else if(finished==='ascent')returnToSpace();}
}
function updateUI(){if(!planets)return;const ground=!!surface&&!universe.group.visible;const p=currentPlanet||planets[selected];$('location-name').textContent=ground?p.name:`Sistema ${hashSeed(seedText).toString(16).slice(0,5).toUpperCase()}`;$('biome-label').textContent=ground?p.type:'ESPACIO PROFUNDO';$('environment').textContent=ground?`${p.temperature} / ATMÓSFERA ${p.atmosphere.toUpperCase()} / VIDA ${p.life.toUpperCase()}`:`DESTINO ${planets[selected].name.toUpperCase()} / RUTA LIBRE`;if(!ground)$('environment').textContent=`CASCO ${Math.round(hullTemperature)}°C / ${hullTemperature>100?'⚠ SOBRECALENTAMIENTO':solarExposure(player.position.length())>0?'⚠ RADIACIÓN SOLAR':'DESTINO '+p.name.toUpperCase()} / ÓRBITA ${Math.round(p.orbitRadius)} M`; $('speed').textContent=Math.round(speed);$('altitude').textContent=ground?`${Math.max(0,Math.round((mode==='walking'?walker.y:player.position.y)-surface.height(mode==='walking'?walker.x:player.position.x,mode==='walking'?walker.z:player.position.z)))} M`:'ÓRBITA';$('shield-bar').style.width=`${shield}%`;$('shield-value').textContent=Math.ceil(shield);$('boost-bar').style.width=`${boost}%`;$('boost-value').textContent=Math.round(boost);$('discovered-count').textContent=planets.filter(p=>p.discovered).length;$('planet-total').textContent=planets.length;$('scan-count').textContent=`${scans} HALLAZGOS CATALOGADOS`;$('player-label').textContent=mode==='walking'?'EXOTRAJE / EXPLORADOR':'VANGUARD / EXPLORADOR';$('secondary-label').textContent=mode==='walking'?'RESERVA':'PROPULSIÓN';$('wave-label').textContent=`PATRULLA HOSTIL / ${battleWave} DE 3`;$('enemy-count').textContent=`${enemies.length} HOSTILES`;$('score-label').textContent=`${String(score).padStart(5,'0')} U`;
  let title='',detail='',hints='';if(mode==='space'){title=`VISITAR ${planets[selected].name.toUpperCase()}`;detail='Pulso interplanetario y entrada atmosférica';hints='<span><b>RATÓN</b> DIRIGIR</span><span><b>W S</b> VELOCIDAD</span><span><b>1–9</b> DESTINO</span><span><b>X</b> FRENAR</span><span><b>B</b> COMBATE</span><span><b>ESC</b> PAUSA</span>';}else if(mode==='surface'){title='ATERRIZAR';detail=landingPreview?`ZONA SEGURA A ${Math.round(Math.hypot(player.position.x-landingPreview.x,player.position.z-landingPreview.z))} M · FRENADO ${Math.ceil(stoppingDistance(speed))} M`:'SIN ZONA SEGURA · BUSCA TERRENO LLANO Y DESPEJADO';hints='<span><b>RATÓN</b> DIRIGIR</span><span><b>W S</b> VELOCIDAD</span><span><b>SHIFT</b> 900 M/S</span><span><b>R</b> VOLVER AL ESPACIO</span><span><b>X</b> FRENAR</span><span><b>L</b> LUGARES</span><span><b>C</b> FOTO</span>';}else if(mode==='landed'){title='SALIR DE LA NAVE';detail='Da tus primeros pasos en un mundo nuevo';hints='<span><b>R</b> DESPEGAR</span><span><b>F</b> ESCANEAR</span><span><b>C</b> FOTO</span><span><b>ESC</b> PAUSA</span>';}else if(mode==='walking'){const near=walker.distanceTo(player.position)<20;title=near?'SUBIR A LA NAVE':'EXPLORACIÓN A PIE';detail=near?'Tu siguiente horizonte está ahí fuera':`Nave a ${Math.round(walker.distanceTo(player.position))} m · F para escanear`;hints='<span><b>ARRASTRAR</b> CÁMARA</span><span><b>RUEDA</b> ZOOM</span><span><b>WASD</b> CAMINAR</span><span><b>SHIFT</b> CORRER</span><span><b>ESPACIO</b> SALTAR</span><span><b>F</b> ESCANEAR</span><span><b>C</b> FOTO</span>';}else if(['transit','descent','ascent','landing','takeoff','generating'].includes(mode)){title='';}else return;
  $('interaction').hidden=!title||cinematic;$('action-title').textContent=title;$('action-detail').textContent=detail;$('action-key').textContent=mode==='walking'&&walker.distanceTo(player.position)>=20?'F':'E';if($('key-hints').innerHTML!==hints)$('key-hints').innerHTML=hints;canvas.dataset.mode=mode;canvas.dataset.planet=currentPlanet?.name||'';
}
function project(position,element,allowEdge=false){const screen=position.clone().project(camera),inFront=position.clone().sub(camera.position).dot(forward.clone().applyQuaternion(camera.quaternion))>0;const visible=inFront&&Math.abs(screen.x)<.96&&Math.abs(screen.y)<.84;if(!visible&&!allowEdge){element.hidden=true;return;}element.hidden=false;let x=screen.x,y=-screen.y;if(!visible){x*=inFront?1:-1;y*=inFront?1:-1;const divisor=Math.max(Math.abs(x)/.82,Math.abs(y)/.57,1);x/=divisor;y/=divisor;}element.style.left=`${(x*.5+.5)*innerWidth}px`;element.style.top=`${(y*.5+.5)*innerHeight}px`;}
function updateMarkers(){camera.updateMatrixWorld();planetMarkers.forEach((m,i)=>{if(mode!=='space'){m.hidden=true;return;}const p=planets[i];project(vec(...p.position),m,i===selected);m.querySelector('strong').textContent=p.name;m.querySelector('small').textContent=`${Math.max(0,Math.round(player.position.distanceTo(vec(...p.position))-p.radius))} KM · ${i+1}`;});for(const e of enemies){project(e.mesh.position,e.marker,true);e.marker.firstElementChild.textContent=`${Math.round(e.mesh.position.distanceTo(player.position))} M`;}for(const m of scanMarkers){if(scanTimer>0&&surface)project(m.resource.position,m.element);else m.element.hidden=true;}}
function updateSurfaceNavigation(dt){
  if(siteSurface!==surface){for(const marker of siteMarkers)marker.remove();siteMarkers.length=0;siteSurface=surface;siteIndex=0;landingPreview=null;landingCheckTimer=0;hazardTimer=0;if(surface)for(const site of surface.landmarks){const marker=document.createElement('div');marker.className='site-marker';const title=document.createElement('strong'),detail=document.createElement('small');title.textContent=site.name;marker.append(title,detail);$('markers').append(marker);siteMarkers.push(marker);}}
  const visible=!!surface&&!cinematic&&['surface','walking','landed','landing','takeoff'].includes(mode);siteNav.hidden=!visible;
  for(const marker of siteMarkers)marker.hidden=!visible;if(!visible)return;
  const origin=mode==='walking'?walker:player.position,selectedSite=siteIndex%surface.landmarks.length;
  surface.landmarks.forEach((site,i)=>{const marker=siteMarkers[i],distance=origin.distanceTo(site.position);marker.classList.toggle('selected',i===selectedSite);marker.querySelector('small').textContent=`${Math.round(distance)} M${site.hazard?' · '+site.hazard.toUpperCase():''}${site.scanned?' · REGISTRADO':''}`;project(site.position,marker,i===selectedSite);});
  const site=surface.landmarks[selectedSite];siteNav.textContent=`L · ${site.name} · ${Math.round(origin.distanceTo(site.position))} M ↗`;
  const hazard=surface.hazardAt(origin.x,origin.z),closeToGround=origin.y-surface.height(origin.x,origin.z)<35;
  if(hazard&&closeToGround&&dt>0){hazardTimer+=dt;if(hazardTimer>=2){hazardTimer=0;shield=Math.max(1,shield-6);lastDamage=gameTime;notify(`${hazard.hazard.toUpperCase()} · ABANDONA LA CUENCA`,2);}}else hazardTimer=0;
}
function animate(){requestAnimationFrame(animate);const rawDelta=clock.getDelta(),dt=Math.min(rawDelta,.04),travelDelta=Math.min(rawDelta,.12);if(mode!=='paused'&&mode!=='generating')elapsed+=dt;const resolution=renderBudget.sample(rawDelta,['space','surface','walking'].includes(mode));if(resolution!==null){renderer.setPixelRatio(resolution);postprocessing.resize();}
  if(mode==='menu'){const p=planets[selected],mobile=innerWidth<700;const target=vec(...p.position);camera.position.copy(target).add(vec(-p.radius*(mobile?.65:1.0),p.radius*.20,p.radius*(mobile?3.1:3.25)));camera.up.copy(up);camera.lookAt(target.clone().add(vec(-p.radius*(mobile?.50:.85),-p.radius*.15,0)));camera.fov=mobile?64:55;camera.updateProjectionMatrix();player.position.copy(vec(mobile?6.7:12,mobile?-6:-6,-29).applyQuaternion(camera.quaternion).add(camera.position));player.quaternion.copy(camera.quaternion).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(.24,-.6+Math.sin(elapsed*.1)*.07,-.2)));player.position.y+=Math.sin(elapsed*.6)*.2;}
  if(['space','surface','walking','landed'].includes(mode)){gameTime+=dt;if(mode==='walking')updateWalking(dt);else if(mode==='landed'){speed=0;followCamera(dt);}else updateFlight(dt);heat=Math.max(0,heat-25*dt);if(overheated&&heat<30)overheated=false;if(gameTime-lastDamage>5)shield=Math.min(100,shield+8*dt);updateCombat(dt);}
  if(['transit','descent','ascent','landing','takeoff'].includes(mode))updateTransition(travelDelta);
  if(mode!=='paused'&&atmosphereRelease>0){atmosphereRelease=Math.max(0,atmosphereRelease-travelDelta);atmosphereCover=easeFlight(atmosphereRelease/.65);}
  if(mode!=='paused'){notifyTimer-=dt;discoveryTimer-=dt;scanTimer-=dt;if(notifyTimer<=0)$('notification').classList.remove('show');if(discoveryTimer<=0)$('discovery').hidden=true;damageFlash=Math.max(0,damageFlash-dt);$('damage-flash').style.opacity=damageFlash;}
  if(surface&&!universe.group.visible){surface.update(elapsed,mode==='paused'?0:dt,camera,mode==='walking'?walker:player.position);surface.landingEffects.update(mode==='paused'?0:dt,player.position,['surface','landing','takeoff','descent'].includes(mode),speed);if(mode==='surface'){landingCheckTimer-=dt;if(landingCheckTimer<=0)refreshLandingPreview();}surface.landingEffects.setGuide(landingPreview,!cinematic&&['surface','landing'].includes(mode));const focus=mode==='walking'?walker:player.position;sun.position.copy(focus).add(vec(-450,520,-300));sun.target.position.copy(focus);}else {universe.update(elapsed,camera,mode==='paused'?0:dt);sun.position.set(0,0,0);sun.target.position.copy(player.position);sun.intensity=.45;}
  for(const child of player.children){if(child.userData.landingGear)child.visible=['landed','walking'].includes(mode)||(mode==='landing'&&transition&&transition.time/transition.duration>.6);if(child.userData.engine&&['landed','walking'].includes(mode))child.scale.setScalar(.65);}
  updatePlayerShip(player,elapsed,speed,['landed','walking'].includes(mode));
  if(avatar)avatar.mesh.visible=mode==='walking'||(mode==='paused'&&previousMode==='walking');dust.visible=mode==='space'||mode==='transit';dust.position.copy(player.position);player.visible=!(firstPerson&&['space','surface'].includes(mode));combatEffects.update(mode==='paused'?0:dt);gameAudio.update(mode,speed,transition?transition.time/transition.duration:0,keys.has('KeyX'));updateUI();updateMarkers();updateSurfaceNavigation(mode==='paused'?0:dt);postprocessing.setAtmosphere(atmosphereCover,atmosphereTint);renderRelative(scene,camera,()=>postprocessing.render(elapsed,!!surface&&!universe.group.visible));
}

$('launch').onclick=startGame;$('regenerate').onclick=()=>{if(mode==='menu'){const seed=`SKY-${Date.now().toString(36).toUpperCase()}`;rebuildUniverse(seed);}};$('seed').addEventListener('change',()=>{if(mode==='menu')rebuildUniverse($('seed').value);});$('seed').addEventListener('keydown',e=>{e.stopPropagation();if(e.code==='Enter'){$('seed').blur();}});
$('help').onclick=showHelp;$('atlas').onclick=showAtlas;$('home').onclick=()=>mode==='menu'?showHelp():pause();$('return-hangar').onclick=returnMenu;function updateSoundButton(){$('sound').style.color=gameAudio.enabled?'#e6efb6':'';$('sound').textContent=gameAudio.enabled?'♫':'♪';$('sound').setAttribute('aria-label',gameAudio.enabled?'Silenciar sonido':'Activar sonido');$('sound').title=gameAudio.enabled?'Silenciar sonido':'Activar sonido';} $('sound').onclick=()=>{gameAudio.setEnabled(!gameAudio.enabled);updateSoundButton();};updateSoundButton();
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('fullscreen').title='No disponible en este navegador';notify('PANTALLA COMPLETA NO DISPONIBLE',3);}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(renderBudget.ratio);postprocessing.resize();});
window.addEventListener('keydown',e=>{if(document.activeElement?.tagName==='INPUT')return;if(e.code==='Escape'){if(cinematic){cinematic=false;$('hud').hidden=false;document.querySelector('.topbar').hidden=false;}else if(mode==='paused')resume();else if(mode==='menu')$('modal').hidden=true;else pause();return;}if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&mode!=='menu')e.preventDefault();if(e.repeat)return;if(mode==='paused'||!$('modal').hidden)return;if(e.code==='Space'&&mode==='walking'){walkingMotion.requestJump();return;}if(e.code==='Tab'){showAtlas();return;}if(e.code==='KeyE'){action();return;}if(e.code==='KeyR'){if(mode==='landed'||mode==='walking')takeoff();else if(mode==='surface')beginAscent();return;}if(e.code==='KeyL'&&surface){siteIndex++;return;}if(e.code==='KeyF'){scan();return;}if(e.code==='KeyB'&&mode==='space'&&!battleWave){spawnWave();return;}if(e.code==='KeyV'){if(mode!=='walking')firstPerson=!firstPerson;return;}if(e.code==='KeyC'&&mode!=='menu'){cinematic=!cinematic;$('hud').hidden=cinematic;document.querySelector('.topbar').hidden=cinematic;return;}if(/^Digit[1-9]$/.test(e.code)&&mode==='space'){selectPlanet(Number(e.code.slice(-1))-1);return;}keys.add(e.code);});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!['space','surface','walking'].includes(mode))return;if(mode==='walking')return;pointer.x=clamp((e.clientX/innerWidth-.5)*2,-1,1);pointer.y=clamp((e.clientY/innerHeight-.5)*2,-1,1);if(Math.abs(pointer.x)<.06)pointer.x=0;if(Math.abs(pointer.y)<.06)pointer.y=0;});canvas.addEventListener('pointerdown',e=>{if(mode==='space'&&e.button===0){firing=true;firePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);}});window.addEventListener('pointerup',e=>{if(e.pointerId===firePointer){firing=false;firePointer=null;}});window.addEventListener('blur',()=>{resetInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInput();pause();}});
$('touch-action').onclick=action;$('touch-scan').onclick=scan;$('touch-takeoff').onclick=()=>mode==='surface'?beginAscent():takeoff();for(const [id,setter] of [['touch-fire',v=>firing=v],['touch-boost',v=>touchBoost=v]]){const el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);setter(true);});el.addEventListener('pointerup',()=>setter(false));el.addEventListener('pointercancel',()=>setter(false));}
const joystick=$('joystick');function moveJoystick(e){const r=joystick.getBoundingClientRect();pointer.x=clamp((e.clientX-r.left-r.width/2)/35,-1,1);pointer.y=clamp((e.clientY-r.top-r.height/2)/35,-1,1);joystick.firstElementChild.style.transform=`translate(${pointer.x*25}px,${pointer.y*25}px)`;}joystick.addEventListener('pointerdown',e=>{joystickId=e.pointerId;joystick.setPointerCapture(e.pointerId);moveJoystick(e);});joystick.addEventListener('pointermove',e=>{if(joystickId===e.pointerId)moveJoystick(e);});for(const type of ['pointerup','pointercancel'])joystick.addEventListener(type,()=>{joystickId=null;pointer.x=pointer.y=0;joystick.firstElementChild.style.transform='';});
async function bootstrap(){
  try{
    $('loading-message').textContent='CARGANDO NAVES, ASTEROIDES Y EXPLORADORES';
    const [loaded]=await Promise.all([loadPlayerShip(),loadAssetLibrary()]);
    player.add(...loaded.children.slice());player.userData.credit=loaded.userData.credit;canvas.dataset.ship='Rusty Spaceship - Orange';
    avatar=createExplorer(0);avatar.mesh.visible=false;scene.add(avatar.mesh);rebuildUniverse(seedText);setMode('menu');animate();$('loading').hidden=true;
  }catch(error){console.error(error);$('loading').innerHTML='<span class="loading-logo">NO AI’ SKY</span><p class="fatal">No se ha podido cargar la nave. Comprueba que el servidor local siga activo y vuelve a intentarlo.</p><button class="primary" id="retry-loading">REINTENTAR <span>↗</span></button>';$('retry-loading').onclick=()=>location.reload();}
}
bootstrap();

canvas.addEventListener('contextmenu',e=>{if(mode==='walking')e.preventDefault();});
canvas.addEventListener('pointerdown',e=>{if(mode!=='walking')return;orbitPointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(mode!=='walking'||orbitPointer?.id!==e.pointerId)return;walkingYaw-=(e.clientX-orbitPointer.x)*.004;walkingPitch=clamp(walkingPitch-(e.clientY-orbitPointer.y)*.003,-.75,.55);orbitPointer.x=e.clientX;orbitPointer.y=e.clientY;});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(orbitPointer?.id===e.pointerId)orbitPointer=null;});
canvas.addEventListener('wheel',e=>{if(mode!=='walking')return;e.preventDefault();walkingCamera.zoom(e.deltaY);},{passive:false});
